language: node_js
node_js:
  - node

git:
  depth: false

sudo: required
dist: trusty
group: edge

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - g++-4.8
      - google-chrome-stable

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  # package-lock.json was introduced in npm@5
  - "[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest" # skipped when using node 9

after_success:
  - npm run coveralls
